/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SalesPersonService } from "../salesPerson.service";
import { SalesPersonCreateInput } from "./SalesPersonCreateInput";
import { SalesPerson } from "./SalesPerson";
import { SalesPersonFindManyArgs } from "./SalesPersonFindManyArgs";
import { SalesPersonWhereUniqueInput } from "./SalesPersonWhereUniqueInput";
import { SalesPersonUpdateInput } from "./SalesPersonUpdateInput";

export class SalesPersonControllerBase {
  constructor(protected readonly service: SalesPersonService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SalesPerson })
  async createSalesPerson(
    @common.Body() data: SalesPersonCreateInput
  ): Promise<SalesPerson> {
    return await this.service.createSalesPerson({
      data: data,
      select: {
        createdAt: true,
        department: true,
        email: true,
        firstName: true,
        hireDate: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SalesPerson] })
  @ApiNestedQuery(SalesPersonFindManyArgs)
  async salesPeople(@common.Req() request: Request): Promise<SalesPerson[]> {
    const args = plainToClass(SalesPersonFindManyArgs, request.query);
    return this.service.salesPeople({
      ...args,
      select: {
        createdAt: true,
        department: true,
        email: true,
        firstName: true,
        hireDate: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SalesPerson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async salesPerson(
    @common.Param() params: SalesPersonWhereUniqueInput
  ): Promise<SalesPerson | null> {
    const result = await this.service.salesPerson({
      where: params,
      select: {
        createdAt: true,
        department: true,
        email: true,
        firstName: true,
        hireDate: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SalesPerson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSalesPerson(
    @common.Param() params: SalesPersonWhereUniqueInput,
    @common.Body() data: SalesPersonUpdateInput
  ): Promise<SalesPerson | null> {
    try {
      return await this.service.updateSalesPerson({
        where: params,
        data: data,
        select: {
          createdAt: true,
          department: true,
          email: true,
          firstName: true,
          hireDate: true,
          id: true,
          lastName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SalesPerson })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSalesPerson(
    @common.Param() params: SalesPersonWhereUniqueInput
  ): Promise<SalesPerson | null> {
    try {
      return await this.service.deleteSalesPerson({
        where: params,
        select: {
          createdAt: true,
          department: true,
          email: true,
          firstName: true,
          hireDate: true,
          id: true,
          lastName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
